name: bookeat
description: BookEat
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

# * Application Packages and Libraries
# * Flutter Packages overrides for conflict resolution
dependency_overrides:
  intl: ^0.18.1

dependencies:



  dio: ^5.1.1
  equatable: ^2.0.7


  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.13.10
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.2.3
  hive_flutter: ^1.1.0
  image: ^4.0.17
  image_picker: ^1.1.2
  injectable: ^2.1.1
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.5
  intl_utils: ^2.8.10
  introduction_screen: ^3.1.17
  js: ^0.7.2
  jwt_decode: ^0.3.1
  l: ^5.0.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0


# * Packages that will not be in the release version of app
dev_dependencies:
  bloc_test: ^10.0.0

  # * Code Generators
  # Generating Files
  build_runner: ^2.4.6

  # * UI Testing
  # Generate Fake Data
  faker: ^2.0.0
  # Generating Asset Files
  flutter_gen_runner: ^5.1.0+1

  # * Linter and code organization
  # Linter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # Code Generation for Models and Union Types
  freezed: ^2.2.0
  # Injecting Dependencies
  injectable_generator: ^2.1.1
  # Generating Serialization of JSON
  json_serializable: ^6.5.4
  # Data Mocking
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/app_images/
    - assets/splash/
    - assets/fonts/
    - assets/documents/

  fonts:
    - family: app_icons
      fonts:
        - asset: assets/fonts/app_icons.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

# * Localizations generating config
flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/intl
  output_dir: lib/src/core/localization/generated
  class_name: S # This is the default class name for the generated delegate
  main_locale: ru # Specify your main locale
  translate_var: loc # This matches your context.loc usage

# * Flutter Icon Generator Configurations
flutter_icons:
  image_path: "assets/icons/stage.png"
  # Android Icon
  android: true
  adaptive_icon_background: "#1E1E1E"
  # iOS Icon
  ios: true
  remove_alpha_ios: true
